export const changelogData = [
  {
    version: "0.2.8",
    date: "2025-07-01",
    type: "feature",
    changes: [
      "Improved concurrent processing of links",
      "Better link check concurrency",
      "Improved Page Speed Bulk Analysis",
      "Added log project segmentation",
      "Improved log search",
      "added filter for User Agents",
      "Added IP masking on logs table",
      "Improved speed on log processing",
      "Better log batch upload and reload",
      "Improved log table UI",
      "Better date selection for GA4",
      "Improved error handling of APIs",
    ],
  },
  {
    version: "0.2.7",
    date: "2025-06-17",
    type: "fix",
    changes: [
      "Support for partial and full App reset",
      "Better handling of configuration folders & files",
      "Improved tables on Deep crawler",
    ],
  },

  {
    version: "0.2.6",
    date: "2025-06-15",
    type: "fix",
    changes: [
      "Table rows not rendering correctly",
      "Better status code colouring",
      "Fixed Google Ads Simulator ",
    ],
  },
  {
    version: "0.2.5",
    date: "2025-06-01",
    type: "update",
    changes: [
      "Performance Improvements",
      "Inlinks & Outlinks improvements",
      "Improved incremental log analysis",
      "Log analyser: improved search",
      "Global system info",
      "Deep Crawl: context menus added to tables",
    ],
  },
  {
    version: "0.2.4",
    date: "2025-05-25",
    type: "update",
    changes: [
      "Microsoft Power BI integration",
      "Incremental log analysis",
      "Log storage and retrieval",
      "Parallel log parsing",
      "Improved log filtering",
      "PPC simulator added",
      "Improved filtering on Logs",
      "Improved Google bot Frequency calculation",
      "Tables UI improvements",
      "Bulk Page Speed Insights on Deep crawler",
      "Deep crawler performance improvements",
      "Request status codes on in/out links",
    ],
  },
  {
    version: "0.2.3",
    date: "2025-01-28",
    type: "feature",
    changes: [
      "Shallow Crawl page schema validator",
      "Onboarding Introduction",
      "GSC Keyword Tracking",
      "Deep Crawl Custom Search",
    ],
  },
];
