export const changelogData = [
  {
    version: "0.3.4",
    date: "2025-12-25",
    type: "feature",
    changes: ["Log analyser: Table segments"],
  },
  {
    version: "0.3.3",
    date: "2025-12-01",
    type: "feature",
    changes: [
      "Log Analyser: More content segments",
      "Log analyser: OpenAI bot validation",
      "Log Analyser: Bing bot validation ",
      "Log Analyser: WP Rocket detection",
    ],
  },

  {
    version: "0.3.2",
    date: "2025-11-01",
    type: "feature",
    changes: [
      "Page Speed Insights Better Rate Limiting & URL encoding",
      "PSI improved UI",
      "PSI status log",
      "Logs: User agent segments added",
    ],
  },
  {
    version: "0.3.1",
    date: "2025-10-01",
    type: "feature",
    changes: ["Bug fixes and improvements"],
  },
  {
    version: "0.3.0",
    date: "2025-09-01",
    type: "feature",
    changes: [
      "Deep Crawl: Configurable stop words",
      "Deep Crawl: GSC queries and metrics",
      "Deep Crawl: Added robots parsin",
    ],
  },
  {
    version: "0.2.9",
    date: "2025-08-17",
    type: "fix",
    changes: [
      "PPC Ads simulator with better export CSV",
      "PPC Improved UI & UX",
      "Better deep crawl finish notification",
      "Improved deep crawl URL tracking",
      "Bulk Image resizing Tool",
      "Google Search Console matching in Deep Crawl",
    ],
  },
  {
    version: "0.2.8",
    date: "2025-07-01",
    type: "feature",
    changes: [
      "Other fixes",
      "Deep crawl tables MacOSX bug fix",
      "Improved concurrent processing of links",
      "Better link check concurrency",
      "Improved Page Speed Bulk Analysis",
      "Added log project segmentation",
      "Improved log search",
      "added filter for User Agents",
      "Added IP masking on logs table",
      "Improved speed on log processing",
      "Better log batch upload and reload",
      "Improved log table UI",
      "Better date selection for GA4",
      "Improved error handling of APIs",
    ],
  },
  {
    version: "0.2.7",
    date: "2025-06-17",
    type: "fix",
    changes: [
      "Support for partial and full App reset",
      "Better handling of configuration folders & files",
      "Improved tables on Deep crawler",
    ],
  },

  {
    version: "0.2.6",
    date: "2025-06-15",
    type: "fix",
    changes: [
      "Table rows not rendering correctly",
      "Better status code colouring",
      "Fixed Google Ads Simulator ",
    ],
  },
  {
    version: "0.2.5",
    date: "2025-06-01",
    type: "update",
    changes: [
      "Performance Improvements",
      "Inlinks & Outlinks improvements",
      "Improved incremental log analysis",
      "Log analyser: improved search",
      "Global system info",
      "Deep Crawl: context menus added to tables",
    ],
  },
  {
    version: "0.2.4",
    date: "2025-05-25",
    type: "update",
    changes: [
      "Microsoft Power BI integration",
      "Incremental log analysis",
      "Log storage and retrieval",
      "Parallel log parsing",
      "Improved log filtering",
      "PPC simulator added",
      "Improved filtering on Logs",
      "Improved Google bot Frequency calculation",
      "Tables UI improvements",
      "Bulk Page Speed Insights on Deep crawler",
      "Deep crawler performance improvements",
      "Request status codes on in/out links",
    ],
  },
  {
    version: "0.2.3",
    date: "2025-01-28",
    type: "feature",
    changes: [
      "Shallow Crawl page schema validator",
      "Onboarding Introduction",
      "GSC Keyword Tracking",
      "Deep Crawl Custom Search",
    ],
  },
];
